name: tcc_maua_2022
description: Projeto em Flutter para o TCC 2022.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+5
  dio: ^4.0.6
  intl: ^0.17.0
  build_runner: ^2.2.0
  extended_masked_text: ^2.3.1
  mobx_codegen: ^2.0.7
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+1
  mask_text_input_formatter: ^2.4.0
  mockito: ^5.3.1
  modular_test: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

scripts:
  mobx_build: flutter pub run build_runner build 
  mobx_watch: flutter pub run build_runner watch --delete-conflicting-outputs